PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCAWF_VM_OMSRLAS CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
 MODULE FILL_SUBSTFLDS.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZCAWF_VM_OMSRLAS-SEQNO .
    FIELD ZCAWF_VM_OMSRLAS-APPROVING_JOB .
    FIELD ZCAWF_VM_OMSRLAS-SIGN_APPR_JOB .
    FIELD ZCAWF_VM_OMSRLAS-SELF_APPROVING_JOB .
    FIELD ZCAWF_VM_OMSRLAS-SIGN_SELF_APPR_JOB .
    FIELD ZCAWF_VM_OMSRLAS-TASK_2_DELEGATE .
    FIELD ZCAWF_VM_OMSRLAS-STEXT_JOB .
    FIELD ZCAWF_VM_OMSRLAS-STEXT_TASK .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
    MODULE COMPLETE_ZCAWF_VM_OMSRLAS ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZCAWF_VM_OMSRLAS-SEQNO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
