PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCAWF_VM_OMTASK CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
   MODULE LISTE_DEACTIVATE.                         "SCH-20250723-110331
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZCAWF_VM_OMTASK-TASK_ID .
    FIELD ZCAWF_VM_OMTASK-ENDDA .
    FIELD ZCAWF_VM_OMTASK-BEGDA .
    FIELD ZCAWF_VM_OMTASK-STEXT .
    FIELD ZCAWF_VM_OMTASK-SHORT .
    FIELD ZCAWF_VM_OMTASK-BEGDA_OM .
    FIELD ZCAWF_VM_OMTASK-ENDDA_OM .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   CHAIN.                                           "SCH-20250723-110331
    FIELD ZCAWF_VM_OMTASK-BEGDA.                    "SCH-20250723-110331
    FIELD ZCAWF_VM_OMTASK-ENDDA.                    "SCH-20250723-110331
    MODULE TEMP_DELIMITATION ON CHAIN-REQUEST.      "SCH-20250723-110331
   ENDCHAIN.                                        "SCH-20250723-110331
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZCAWF_VM_OMTASK-TASK_ID .
    FIELD ZCAWF_VM_OMTASK-ENDDA .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
