PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCAWF_VM_OMSRLVL CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
   MODULE LISTE_DEACTIVATE.                         "SCH-20250723-110317
 ENDLOOP.
 MODULE FILL_SUBSTFLDS.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZCAWF_VM_OMSRLVL-SRULE_LEVEL .
    FIELD ZCAWF_VM_OMSRLVL-ENDDA .
    FIELD ZCAWF_VM_OMSRLVL-BEGDA .
    FIELD ZCAWF_VM_OMSRLVL-DESCRIPTION .
    FIELD ZCAWF_VM_OMSRLVL-DESCR_SHORT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   CHAIN.                                           "SCH-20250723-110317
    FIELD ZCAWF_VM_OMSRLVL-BEGDA.                   "SCH-20250723-110317
    FIELD ZCAWF_VM_OMSRLVL-ENDDA.                   "SCH-20250723-110317
    MODULE TEMP_DELIMITATION ON CHAIN-REQUEST.      "SCH-20250723-110317
   ENDCHAIN.                                        "SCH-20250723-110317
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZCAWF_VM_OMSRLVL-SRULE_LEVEL .
    FIELD ZCAWF_VM_OMSRLVL-ENDDA .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
