*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZCAWF_VM_OMJOB..................................*
FORM GET_DATA_ZCAWF_VM_OMJOB.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZCAWF_OM_SRJOB WHERE
(VIM_WHERETAB) .
    CLEAR ZCAWF_VM_OMJOB .
ZCAWF_VM_OMJOB-MANDT =
ZCAWF_OM_SRJOB-MANDT .
ZCAWF_VM_OMJOB-JOB_ID =
ZCAWF_OM_SRJOB-JOB_ID .
ZCAWF_VM_OMJOB-ENDDA =
ZCAWF_OM_SRJOB-ENDDA .
ZCAWF_VM_OMJOB-BEGDA =
ZCAWF_OM_SRJOB-BEGDA .
ZCAWF_VM_OMJOB-STEXT =
ZCAWF_OM_SRJOB-STEXT .
ZCAWF_VM_OMJOB-SHORT =
ZCAWF_OM_SRJOB-SHORT .
ZCAWF_VM_OMJOB-BEGDA_OM =
ZCAWF_OM_SRJOB-BEGDA_OM .
ZCAWF_VM_OMJOB-ENDDA_OM =
ZCAWF_OM_SRJOB-ENDDA_OM .
<VIM_TOTAL_STRUC> = ZCAWF_VM_OMJOB.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZCAWF_VM_OMJOB .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZCAWF_VM_OMJOB.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZCAWF_VM_OMJOB-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZCAWF_OM_SRJOB WHERE
  JOB_ID = ZCAWF_VM_OMJOB-JOB_ID AND
  ENDDA = ZCAWF_VM_OMJOB-ENDDA .
    IF SY-SUBRC = 0.
    DELETE ZCAWF_OM_SRJOB .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZCAWF_OM_SRJOB WHERE
  JOB_ID = ZCAWF_VM_OMJOB-JOB_ID AND
  ENDDA = ZCAWF_VM_OMJOB-ENDDA .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZCAWF_OM_SRJOB.
    ENDIF.
ZCAWF_OM_SRJOB-MANDT =
ZCAWF_VM_OMJOB-MANDT .
ZCAWF_OM_SRJOB-JOB_ID =
ZCAWF_VM_OMJOB-JOB_ID .
ZCAWF_OM_SRJOB-ENDDA =
ZCAWF_VM_OMJOB-ENDDA .
ZCAWF_OM_SRJOB-BEGDA =
ZCAWF_VM_OMJOB-BEGDA .
ZCAWF_OM_SRJOB-STEXT =
ZCAWF_VM_OMJOB-STEXT .
ZCAWF_OM_SRJOB-SHORT =
ZCAWF_VM_OMJOB-SHORT .
ZCAWF_OM_SRJOB-BEGDA_OM =
ZCAWF_VM_OMJOB-BEGDA_OM .
ZCAWF_OM_SRJOB-ENDDA_OM =
ZCAWF_VM_OMJOB-ENDDA_OM .
    IF SY-SUBRC = 0.
    UPDATE ZCAWF_OM_SRJOB ##WARN_OK.
    ELSE.
    INSERT ZCAWF_OM_SRJOB .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZCAWF_VM_OMJOB-UPD_FLAG,
STATUS_ZCAWF_VM_OMJOB-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZCAWF_VM_OMJOB.
  SELECT SINGLE * FROM ZCAWF_OM_SRJOB WHERE
JOB_ID = ZCAWF_VM_OMJOB-JOB_ID AND
ENDDA = ZCAWF_VM_OMJOB-ENDDA .
ZCAWF_VM_OMJOB-MANDT =
ZCAWF_OM_SRJOB-MANDT .
ZCAWF_VM_OMJOB-JOB_ID =
ZCAWF_OM_SRJOB-JOB_ID .
ZCAWF_VM_OMJOB-ENDDA =
ZCAWF_OM_SRJOB-ENDDA .
ZCAWF_VM_OMJOB-BEGDA =
ZCAWF_OM_SRJOB-BEGDA .
ZCAWF_VM_OMJOB-STEXT =
ZCAWF_OM_SRJOB-STEXT .
ZCAWF_VM_OMJOB-SHORT =
ZCAWF_OM_SRJOB-SHORT .
ZCAWF_VM_OMJOB-BEGDA_OM =
ZCAWF_OM_SRJOB-BEGDA_OM .
ZCAWF_VM_OMJOB-ENDDA_OM =
ZCAWF_OM_SRJOB-ENDDA_OM .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZCAWF_VM_OMJOB USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZCAWF_VM_OMJOB-JOB_ID TO
ZCAWF_OM_SRJOB-JOB_ID .
MOVE ZCAWF_VM_OMJOB-ENDDA TO
ZCAWF_OM_SRJOB-ENDDA .
MOVE ZCAWF_VM_OMJOB-MANDT TO
ZCAWF_OM_SRJOB-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZCAWF_OM_SRJOB'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZCAWF_OM_SRJOB TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZCAWF_OM_SRJOB'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZCAWF_VM_OMSRLAS................................*
FORM GET_DATA_ZCAWF_VM_OMSRLAS.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZCAWF_OM_SRLASSM WHERE
(VIM_WHERETAB) .
    CLEAR ZCAWF_VM_OMSRLAS .
ZCAWF_VM_OMSRLAS-MANDT =
ZCAWF_OM_SRLASSM-MANDT .
ZCAWF_VM_OMSRLAS-SRULE_ID =
ZCAWF_OM_SRLASSM-SRULE_ID .
ZCAWF_VM_OMSRLAS-SR_LEVEL =
ZCAWF_OM_SRLASSM-SR_LEVEL .
ZCAWF_VM_OMSRLAS-ENDDA =
ZCAWF_OM_SRLASSM-ENDDA .
ZCAWF_VM_OMSRLAS-SEQNO =
ZCAWF_OM_SRLASSM-SEQNO .
ZCAWF_VM_OMSRLAS-BEGDA =
ZCAWF_OM_SRLASSM-BEGDA .
ZCAWF_VM_OMSRLAS-APPROVING_JOB =
ZCAWF_OM_SRLASSM-APPROVING_JOB .
ZCAWF_VM_OMSRLAS-SIGN_APPR_JOB =
ZCAWF_OM_SRLASSM-SIGN_APPR_JOB .
ZCAWF_VM_OMSRLAS-SELF_APPROVING_JOB =
ZCAWF_OM_SRLASSM-SELF_APPROVING_JOB .
ZCAWF_VM_OMSRLAS-SIGN_SELF_APPR_JOB =
ZCAWF_OM_SRLASSM-SIGN_SELF_APPR_JOB .
ZCAWF_VM_OMSRLAS-TASK_2_DELEGATE =
ZCAWF_OM_SRLASSM-TASK_2_DELEGATE .
    SELECT * FROM ZCAWF_OM_SRJOB WHERE
JOB_ID = ZCAWF_OM_SRLASSM-APPROVING_JOB .
ZCAWF_VM_OMSRLAS-STEXT_JOB =
ZCAWF_OM_SRJOB-STEXT .
      EXIT.
    ENDSELECT.
    SELECT SINGLE * FROM ZCAWF_OM_SRLVL WHERE
SRULE_ID = ZCAWF_OM_SRLASSM-SRULE_ID AND
SRULE_LEVEL = ZCAWF_OM_SRLASSM-SR_LEVEL AND
ENDDA = ZCAWF_OM_SRLASSM-ENDDA .
    IF SY-SUBRC EQ 0.
ZCAWF_VM_OMSRLAS-ENDDA_LVL =
ZCAWF_OM_SRLVL-ENDDA .
ZCAWF_VM_OMSRLAS-BEGDA_LVL =
ZCAWF_OM_SRLVL-BEGDA .
      SELECT SINGLE * FROM ZCAWF_OM_SRLVLTX WHERE
SRULE_ID = ZCAWF_OM_SRLVL-SRULE_ID AND
SRULE_LEVEL = ZCAWF_OM_SRLVL-SRULE_LEVEL AND
ENDDA = ZCAWF_OM_SRLVL-ENDDA AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZCAWF_VM_OMSRLAS-DESCRIPTION_LVL =
ZCAWF_OM_SRLVLTX-DESCRIPTION .
      ENDIF.
    ENDIF.
    SELECT * FROM ZCAWF_OM_SRTASK WHERE
TASK_ID = ZCAWF_OM_SRLASSM-TASK_2_DELEGATE .
ZCAWF_VM_OMSRLAS-STEXT_TASK =
ZCAWF_OM_SRTASK-STEXT .
      EXIT.
    ENDSELECT.
    SELECT SINGLE * FROM ZCAWF_OM_SRULE WHERE
SRULE_ID = ZCAWF_OM_SRLASSM-SRULE_ID .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZCAWF_OM_SRULETX WHERE
SRULE_ID = ZCAWF_OM_SRULE-SRULE_ID AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZCAWF_VM_OMSRLAS-DESCRIPTION_RULE =
ZCAWF_OM_SRULETX-DESCRIPTION .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZCAWF_VM_OMSRLAS.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZCAWF_VM_OMSRLAS .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZCAWF_VM_OMSRLAS.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZCAWF_VM_OMSRLAS-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZCAWF_OM_SRLASSM WHERE
  SRULE_ID = ZCAWF_VM_OMSRLAS-SRULE_ID AND
  SR_LEVEL = ZCAWF_VM_OMSRLAS-SR_LEVEL AND
  ENDDA = ZCAWF_VM_OMSRLAS-ENDDA AND
  SEQNO = ZCAWF_VM_OMSRLAS-SEQNO .
    IF SY-SUBRC = 0.
    DELETE ZCAWF_OM_SRLASSM .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZCAWF_OM_SRLASSM WHERE
  SRULE_ID = ZCAWF_VM_OMSRLAS-SRULE_ID AND
  SR_LEVEL = ZCAWF_VM_OMSRLAS-SR_LEVEL AND
  ENDDA = ZCAWF_VM_OMSRLAS-ENDDA AND
  SEQNO = ZCAWF_VM_OMSRLAS-SEQNO .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZCAWF_OM_SRLASSM.
    ENDIF.
ZCAWF_OM_SRLASSM-MANDT =
ZCAWF_VM_OMSRLAS-MANDT .
ZCAWF_OM_SRLASSM-SRULE_ID =
ZCAWF_VM_OMSRLAS-SRULE_ID .
ZCAWF_OM_SRLASSM-SR_LEVEL =
ZCAWF_VM_OMSRLAS-SR_LEVEL .
ZCAWF_OM_SRLASSM-ENDDA =
ZCAWF_VM_OMSRLAS-ENDDA .
ZCAWF_OM_SRLASSM-SEQNO =
ZCAWF_VM_OMSRLAS-SEQNO .
ZCAWF_OM_SRLASSM-BEGDA =
ZCAWF_VM_OMSRLAS-BEGDA .
ZCAWF_OM_SRLASSM-APPROVING_JOB =
ZCAWF_VM_OMSRLAS-APPROVING_JOB .
ZCAWF_OM_SRLASSM-SIGN_APPR_JOB =
ZCAWF_VM_OMSRLAS-SIGN_APPR_JOB .
ZCAWF_OM_SRLASSM-SELF_APPROVING_JOB =
ZCAWF_VM_OMSRLAS-SELF_APPROVING_JOB .
ZCAWF_OM_SRLASSM-SIGN_SELF_APPR_JOB =
ZCAWF_VM_OMSRLAS-SIGN_SELF_APPR_JOB .
ZCAWF_OM_SRLASSM-TASK_2_DELEGATE =
ZCAWF_VM_OMSRLAS-TASK_2_DELEGATE .
    IF SY-SUBRC = 0.
    UPDATE ZCAWF_OM_SRLASSM ##WARN_OK.
    ELSE.
    INSERT ZCAWF_OM_SRLASSM .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZCAWF_VM_OMSRLAS-UPD_FLAG,
STATUS_ZCAWF_VM_OMSRLAS-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZCAWF_VM_OMSRLAS.
  SELECT SINGLE * FROM ZCAWF_OM_SRLASSM WHERE
SRULE_ID = ZCAWF_VM_OMSRLAS-SRULE_ID AND
SR_LEVEL = ZCAWF_VM_OMSRLAS-SR_LEVEL AND
ENDDA = ZCAWF_VM_OMSRLAS-ENDDA AND
SEQNO = ZCAWF_VM_OMSRLAS-SEQNO .
ZCAWF_VM_OMSRLAS-MANDT =
ZCAWF_OM_SRLASSM-MANDT .
ZCAWF_VM_OMSRLAS-SRULE_ID =
ZCAWF_OM_SRLASSM-SRULE_ID .
ZCAWF_VM_OMSRLAS-SR_LEVEL =
ZCAWF_OM_SRLASSM-SR_LEVEL .
ZCAWF_VM_OMSRLAS-ENDDA =
ZCAWF_OM_SRLASSM-ENDDA .
ZCAWF_VM_OMSRLAS-SEQNO =
ZCAWF_OM_SRLASSM-SEQNO .
ZCAWF_VM_OMSRLAS-BEGDA =
ZCAWF_OM_SRLASSM-BEGDA .
ZCAWF_VM_OMSRLAS-APPROVING_JOB =
ZCAWF_OM_SRLASSM-APPROVING_JOB .
ZCAWF_VM_OMSRLAS-SIGN_APPR_JOB =
ZCAWF_OM_SRLASSM-SIGN_APPR_JOB .
ZCAWF_VM_OMSRLAS-SELF_APPROVING_JOB =
ZCAWF_OM_SRLASSM-SELF_APPROVING_JOB .
ZCAWF_VM_OMSRLAS-SIGN_SELF_APPR_JOB =
ZCAWF_OM_SRLASSM-SIGN_SELF_APPR_JOB .
ZCAWF_VM_OMSRLAS-TASK_2_DELEGATE =
ZCAWF_OM_SRLASSM-TASK_2_DELEGATE .
    SELECT * FROM ZCAWF_OM_SRJOB WHERE
JOB_ID = ZCAWF_OM_SRLASSM-APPROVING_JOB .
ZCAWF_VM_OMSRLAS-STEXT_JOB =
ZCAWF_OM_SRJOB-STEXT .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR ZCAWF_VM_OMSRLAS-STEXT_JOB .
    ENDIF.
    SELECT SINGLE * FROM ZCAWF_OM_SRLVL WHERE
SRULE_ID = ZCAWF_OM_SRLASSM-SRULE_ID AND
SRULE_LEVEL = ZCAWF_OM_SRLASSM-SR_LEVEL AND
ENDDA = ZCAWF_OM_SRLASSM-ENDDA .
    IF SY-SUBRC EQ 0.
ZCAWF_VM_OMSRLAS-ENDDA_LVL =
ZCAWF_OM_SRLVL-ENDDA .
ZCAWF_VM_OMSRLAS-BEGDA_LVL =
ZCAWF_OM_SRLVL-BEGDA .
      SELECT SINGLE * FROM ZCAWF_OM_SRLVLTX WHERE
SRULE_ID = ZCAWF_OM_SRLVL-SRULE_ID AND
SRULE_LEVEL = ZCAWF_OM_SRLVL-SRULE_LEVEL AND
ENDDA = ZCAWF_OM_SRLVL-ENDDA AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZCAWF_VM_OMSRLAS-DESCRIPTION_LVL =
ZCAWF_OM_SRLVLTX-DESCRIPTION .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZCAWF_VM_OMSRLAS-DESCRIPTION_LVL .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZCAWF_VM_OMSRLAS-ENDDA_LVL .
      CLEAR ZCAWF_VM_OMSRLAS-BEGDA_LVL .
      CLEAR ZCAWF_VM_OMSRLAS-DESCRIPTION_LVL .
    ENDIF.
    SELECT * FROM ZCAWF_OM_SRTASK WHERE
TASK_ID = ZCAWF_OM_SRLASSM-TASK_2_DELEGATE .
ZCAWF_VM_OMSRLAS-STEXT_TASK =
ZCAWF_OM_SRTASK-STEXT .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR ZCAWF_VM_OMSRLAS-STEXT_TASK .
    ENDIF.
    SELECT SINGLE * FROM ZCAWF_OM_SRULE WHERE
SRULE_ID = ZCAWF_OM_SRLASSM-SRULE_ID .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZCAWF_OM_SRULETX WHERE
SRULE_ID = ZCAWF_OM_SRULE-SRULE_ID AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZCAWF_VM_OMSRLAS-DESCRIPTION_RULE =
ZCAWF_OM_SRULETX-DESCRIPTION .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZCAWF_VM_OMSRLAS-DESCRIPTION_RULE .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZCAWF_VM_OMSRLAS-DESCRIPTION_RULE .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZCAWF_VM_OMSRLAS USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZCAWF_VM_OMSRLAS-SRULE_ID TO
ZCAWF_OM_SRLASSM-SRULE_ID .
MOVE ZCAWF_VM_OMSRLAS-SR_LEVEL TO
ZCAWF_OM_SRLASSM-SR_LEVEL .
MOVE ZCAWF_VM_OMSRLAS-ENDDA TO
ZCAWF_OM_SRLASSM-ENDDA .
MOVE ZCAWF_VM_OMSRLAS-SEQNO TO
ZCAWF_OM_SRLASSM-SEQNO .
MOVE ZCAWF_VM_OMSRLAS-MANDT TO
ZCAWF_OM_SRLASSM-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZCAWF_OM_SRLASSM'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZCAWF_OM_SRLASSM TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZCAWF_OM_SRLASSM'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZCAWF_VM_OMSRLAS USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZCAWF_OM_SRLASSM-MANDT =
ZCAWF_VM_OMSRLAS-MANDT .
ZCAWF_OM_SRLASSM-SRULE_ID =
ZCAWF_VM_OMSRLAS-SRULE_ID .
ZCAWF_OM_SRLASSM-SR_LEVEL =
ZCAWF_VM_OMSRLAS-SR_LEVEL .
ZCAWF_OM_SRLASSM-ENDDA =
ZCAWF_VM_OMSRLAS-ENDDA .
ZCAWF_OM_SRLASSM-SEQNO =
ZCAWF_VM_OMSRLAS-SEQNO .
ZCAWF_OM_SRLASSM-BEGDA =
ZCAWF_VM_OMSRLAS-BEGDA .
ZCAWF_OM_SRLASSM-APPROVING_JOB =
ZCAWF_VM_OMSRLAS-APPROVING_JOB .
ZCAWF_OM_SRLASSM-SIGN_APPR_JOB =
ZCAWF_VM_OMSRLAS-SIGN_APPR_JOB .
ZCAWF_OM_SRLASSM-SELF_APPROVING_JOB =
ZCAWF_VM_OMSRLAS-SELF_APPROVING_JOB .
ZCAWF_OM_SRLASSM-SIGN_SELF_APPR_JOB =
ZCAWF_VM_OMSRLAS-SIGN_SELF_APPR_JOB .
ZCAWF_OM_SRLASSM-TASK_2_DELEGATE =
ZCAWF_VM_OMSRLAS-TASK_2_DELEGATE .
    SELECT * FROM ZCAWF_OM_SRJOB WHERE
JOB_ID = ZCAWF_OM_SRLASSM-APPROVING_JOB .
ZCAWF_VM_OMSRLAS-STEXT_JOB =
ZCAWF_OM_SRJOB-STEXT .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR ZCAWF_VM_OMSRLAS-STEXT_JOB .
    ENDIF.
    SELECT SINGLE * FROM ZCAWF_OM_SRLVL WHERE
SRULE_ID = ZCAWF_OM_SRLASSM-SRULE_ID AND
SRULE_LEVEL = ZCAWF_OM_SRLASSM-SR_LEVEL AND
ENDDA = ZCAWF_OM_SRLASSM-ENDDA .
    IF SY-SUBRC EQ 0.
ZCAWF_VM_OMSRLAS-ENDDA_LVL =
ZCAWF_OM_SRLVL-ENDDA .
ZCAWF_VM_OMSRLAS-BEGDA_LVL =
ZCAWF_OM_SRLVL-BEGDA .
      SELECT SINGLE * FROM ZCAWF_OM_SRLVLTX WHERE
SRULE_ID = ZCAWF_OM_SRLVL-SRULE_ID AND
SRULE_LEVEL = ZCAWF_OM_SRLVL-SRULE_LEVEL AND
ENDDA = ZCAWF_OM_SRLVL-ENDDA AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZCAWF_VM_OMSRLAS-DESCRIPTION_LVL =
ZCAWF_OM_SRLVLTX-DESCRIPTION .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZCAWF_VM_OMSRLAS-DESCRIPTION_LVL .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZCAWF_VM_OMSRLAS-ENDDA_LVL .
      CLEAR ZCAWF_VM_OMSRLAS-BEGDA_LVL .
      CLEAR ZCAWF_VM_OMSRLAS-DESCRIPTION_LVL .
    ENDIF.
    SELECT * FROM ZCAWF_OM_SRTASK WHERE
TASK_ID = ZCAWF_OM_SRLASSM-TASK_2_DELEGATE .
ZCAWF_VM_OMSRLAS-STEXT_TASK =
ZCAWF_OM_SRTASK-STEXT .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR ZCAWF_VM_OMSRLAS-STEXT_TASK .
    ENDIF.
    SELECT SINGLE * FROM ZCAWF_OM_SRULE WHERE
SRULE_ID = ZCAWF_OM_SRLASSM-SRULE_ID .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZCAWF_OM_SRULETX WHERE
SRULE_ID = ZCAWF_OM_SRULE-SRULE_ID AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZCAWF_VM_OMSRLAS-DESCRIPTION_RULE =
ZCAWF_OM_SRULETX-DESCRIPTION .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZCAWF_VM_OMSRLAS-DESCRIPTION_RULE .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZCAWF_VM_OMSRLAS-DESCRIPTION_RULE .
    ENDIF.
ENDFORM.
*...processing: ZCAWF_VM_OMSRLVL................................*
FORM GET_DATA_ZCAWF_VM_OMSRLVL.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZCAWF_OM_SRLVL WHERE
(VIM_WHERETAB) .
    CLEAR ZCAWF_VM_OMSRLVL .
ZCAWF_VM_OMSRLVL-MANDT =
ZCAWF_OM_SRLVL-MANDT .
ZCAWF_VM_OMSRLVL-SRULE_ID =
ZCAWF_OM_SRLVL-SRULE_ID .
ZCAWF_VM_OMSRLVL-SRULE_LEVEL =
ZCAWF_OM_SRLVL-SRULE_LEVEL .
ZCAWF_VM_OMSRLVL-ENDDA =
ZCAWF_OM_SRLVL-ENDDA .
ZCAWF_VM_OMSRLVL-BEGDA =
ZCAWF_OM_SRLVL-BEGDA .
    SELECT SINGLE * FROM ZCAWF_OM_SRULE WHERE
SRULE_ID = ZCAWF_OM_SRLVL-SRULE_ID .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZCAWF_OM_SRULETX WHERE
SRULE_ID = ZCAWF_OM_SRULE-SRULE_ID AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZCAWF_VM_OMSRLVL-DESCRIPTION_RULE =
ZCAWF_OM_SRULETX-DESCRIPTION .
      ENDIF.
    ENDIF.
    SELECT SINGLE * FROM ZCAWF_OM_SRLVLTX WHERE
SRULE_ID = ZCAWF_OM_SRLVL-SRULE_ID AND
SRULE_LEVEL = ZCAWF_OM_SRLVL-SRULE_LEVEL AND
ENDDA = ZCAWF_OM_SRLVL-ENDDA AND
LANGU = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZCAWF_VM_OMSRLVL-DESCRIPTION =
ZCAWF_OM_SRLVLTX-DESCRIPTION .
ZCAWF_VM_OMSRLVL-DESCR_SHORT =
ZCAWF_OM_SRLVLTX-DESCR_SHORT .
    ENDIF.
<VIM_TOTAL_STRUC> = ZCAWF_VM_OMSRLVL.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZCAWF_VM_OMSRLVL .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZCAWF_VM_OMSRLVL.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZCAWF_VM_OMSRLVL-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZCAWF_OM_SRLVL WHERE
  SRULE_ID = ZCAWF_VM_OMSRLVL-SRULE_ID AND
  SRULE_LEVEL = ZCAWF_VM_OMSRLVL-SRULE_LEVEL AND
  ENDDA = ZCAWF_VM_OMSRLVL-ENDDA .
    IF SY-SUBRC = 0.
    DELETE ZCAWF_OM_SRLVL .
    ENDIF.
    DELETE FROM ZCAWF_OM_SRLVLTX WHERE
    SRULE_ID = ZCAWF_OM_SRLVL-SRULE_ID AND
    SRULE_LEVEL = ZCAWF_OM_SRLVL-SRULE_LEVEL AND
    ENDDA = ZCAWF_OM_SRLVL-ENDDA .
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZCAWF_OM_SRLVL WHERE
  SRULE_ID = ZCAWF_VM_OMSRLVL-SRULE_ID AND
  SRULE_LEVEL = ZCAWF_VM_OMSRLVL-SRULE_LEVEL AND
  ENDDA = ZCAWF_VM_OMSRLVL-ENDDA .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZCAWF_OM_SRLVL.
    ENDIF.
ZCAWF_OM_SRLVL-MANDT =
ZCAWF_VM_OMSRLVL-MANDT .
ZCAWF_OM_SRLVL-SRULE_ID =
ZCAWF_VM_OMSRLVL-SRULE_ID .
ZCAWF_OM_SRLVL-SRULE_LEVEL =
ZCAWF_VM_OMSRLVL-SRULE_LEVEL .
ZCAWF_OM_SRLVL-ENDDA =
ZCAWF_VM_OMSRLVL-ENDDA .
ZCAWF_OM_SRLVL-BEGDA =
ZCAWF_VM_OMSRLVL-BEGDA .
    IF SY-SUBRC = 0.
    UPDATE ZCAWF_OM_SRLVL ##WARN_OK.
    ELSE.
    INSERT ZCAWF_OM_SRLVL .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM ZCAWF_OM_SRLVLTX WHERE
    SRULE_ID = ZCAWF_OM_SRLVL-SRULE_ID AND
    SRULE_LEVEL = ZCAWF_OM_SRLVL-SRULE_LEVEL AND
    ENDDA = ZCAWF_OM_SRLVL-ENDDA AND
    LANGU = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR ZCAWF_OM_SRLVLTX.
ZCAWF_OM_SRLVLTX-SRULE_ID =
ZCAWF_OM_SRLVL-SRULE_ID .
ZCAWF_OM_SRLVLTX-SRULE_LEVEL =
ZCAWF_OM_SRLVL-SRULE_LEVEL .
ZCAWF_OM_SRLVLTX-ENDDA =
ZCAWF_OM_SRLVL-ENDDA .
ZCAWF_OM_SRLVLTX-LANGU =
SY-LANGU .
      ENDIF.
ZCAWF_OM_SRLVLTX-DESCRIPTION =
ZCAWF_VM_OMSRLVL-DESCRIPTION .
ZCAWF_OM_SRLVLTX-DESCR_SHORT =
ZCAWF_VM_OMSRLVL-DESCR_SHORT .
    IF SY-SUBRC = 0.
    UPDATE ZCAWF_OM_SRLVLTX ##WARN_OK.
    ELSE.
    INSERT ZCAWF_OM_SRLVLTX .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZCAWF_VM_OMSRLVL-UPD_FLAG,
STATUS_ZCAWF_VM_OMSRLVL-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZCAWF_VM_OMSRLVL.
  SELECT SINGLE * FROM ZCAWF_OM_SRLVL WHERE
SRULE_ID = ZCAWF_VM_OMSRLVL-SRULE_ID AND
SRULE_LEVEL = ZCAWF_VM_OMSRLVL-SRULE_LEVEL AND
ENDDA = ZCAWF_VM_OMSRLVL-ENDDA .
ZCAWF_VM_OMSRLVL-MANDT =
ZCAWF_OM_SRLVL-MANDT .
ZCAWF_VM_OMSRLVL-SRULE_ID =
ZCAWF_OM_SRLVL-SRULE_ID .
ZCAWF_VM_OMSRLVL-SRULE_LEVEL =
ZCAWF_OM_SRLVL-SRULE_LEVEL .
ZCAWF_VM_OMSRLVL-ENDDA =
ZCAWF_OM_SRLVL-ENDDA .
ZCAWF_VM_OMSRLVL-BEGDA =
ZCAWF_OM_SRLVL-BEGDA .
    SELECT SINGLE * FROM ZCAWF_OM_SRULE WHERE
SRULE_ID = ZCAWF_OM_SRLVL-SRULE_ID .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZCAWF_OM_SRULETX WHERE
SRULE_ID = ZCAWF_OM_SRULE-SRULE_ID AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZCAWF_VM_OMSRLVL-DESCRIPTION_RULE =
ZCAWF_OM_SRULETX-DESCRIPTION .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZCAWF_VM_OMSRLVL-DESCRIPTION_RULE .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZCAWF_VM_OMSRLVL-DESCRIPTION_RULE .
    ENDIF.
    SELECT SINGLE * FROM ZCAWF_OM_SRLVLTX WHERE
SRULE_ID = ZCAWF_OM_SRLVL-SRULE_ID AND
SRULE_LEVEL = ZCAWF_OM_SRLVL-SRULE_LEVEL AND
ENDDA = ZCAWF_OM_SRLVL-ENDDA AND
LANGU = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZCAWF_VM_OMSRLVL-DESCRIPTION =
ZCAWF_OM_SRLVLTX-DESCRIPTION .
ZCAWF_VM_OMSRLVL-DESCR_SHORT =
ZCAWF_OM_SRLVLTX-DESCR_SHORT .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZCAWF_VM_OMSRLVL-DESCRIPTION .
      CLEAR ZCAWF_VM_OMSRLVL-DESCR_SHORT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZCAWF_VM_OMSRLVL USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZCAWF_VM_OMSRLVL-SRULE_ID TO
ZCAWF_OM_SRLVL-SRULE_ID .
MOVE ZCAWF_VM_OMSRLVL-SRULE_LEVEL TO
ZCAWF_OM_SRLVL-SRULE_LEVEL .
MOVE ZCAWF_VM_OMSRLVL-ENDDA TO
ZCAWF_OM_SRLVL-ENDDA .
MOVE ZCAWF_VM_OMSRLVL-MANDT TO
ZCAWF_OM_SRLVL-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZCAWF_OM_SRLVL'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZCAWF_OM_SRLVL TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZCAWF_OM_SRLVL'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE ZCAWF_OM_SRLVL-SRULE_ID TO
ZCAWF_OM_SRLVLTX-SRULE_ID .
MOVE ZCAWF_OM_SRLVL-SRULE_LEVEL TO
ZCAWF_OM_SRLVLTX-SRULE_LEVEL .
MOVE ZCAWF_OM_SRLVL-ENDDA TO
ZCAWF_OM_SRLVLTX-ENDDA .
MOVE SY-LANGU TO
ZCAWF_OM_SRLVLTX-LANGU .
MOVE ZCAWF_VM_OMSRLVL-MANDT TO
ZCAWF_OM_SRLVLTX-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZCAWF_OM_SRLVLTX'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZCAWF_OM_SRLVLTX TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZCAWF_OM_SRLVLTX'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZCAWF_VM_OMSRLVL USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZCAWF_OM_SRLVL-MANDT =
ZCAWF_VM_OMSRLVL-MANDT .
ZCAWF_OM_SRLVL-SRULE_ID =
ZCAWF_VM_OMSRLVL-SRULE_ID .
ZCAWF_OM_SRLVL-SRULE_LEVEL =
ZCAWF_VM_OMSRLVL-SRULE_LEVEL .
ZCAWF_OM_SRLVL-ENDDA =
ZCAWF_VM_OMSRLVL-ENDDA .
ZCAWF_OM_SRLVL-BEGDA =
ZCAWF_VM_OMSRLVL-BEGDA .
    SELECT SINGLE * FROM ZCAWF_OM_SRULE WHERE
SRULE_ID = ZCAWF_OM_SRLVL-SRULE_ID .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZCAWF_OM_SRULETX WHERE
SRULE_ID = ZCAWF_OM_SRULE-SRULE_ID AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZCAWF_VM_OMSRLVL-DESCRIPTION_RULE =
ZCAWF_OM_SRULETX-DESCRIPTION .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZCAWF_VM_OMSRLVL-DESCRIPTION_RULE .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZCAWF_VM_OMSRLVL-DESCRIPTION_RULE .
    ENDIF.
ENDFORM.
*...processing: ZCAWF_VM_OMSRULE................................*
FORM GET_DATA_ZCAWF_VM_OMSRULE.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZCAWF_OM_SRULE WHERE
(VIM_WHERETAB) .
    CLEAR ZCAWF_VM_OMSRULE .
ZCAWF_VM_OMSRULE-MANDT =
ZCAWF_OM_SRULE-MANDT .
ZCAWF_VM_OMSRULE-SRULE_ID =
ZCAWF_OM_SRULE-SRULE_ID .
    SELECT SINGLE * FROM ZCAWF_OM_SRULETX WHERE
SRULE_ID = ZCAWF_OM_SRULE-SRULE_ID AND
LANGU = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZCAWF_VM_OMSRULE-DESCRIPTION =
ZCAWF_OM_SRULETX-DESCRIPTION .
ZCAWF_VM_OMSRULE-DESCR_SHORT =
ZCAWF_OM_SRULETX-DESCR_SHORT .
    ENDIF.
<VIM_TOTAL_STRUC> = ZCAWF_VM_OMSRULE.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZCAWF_VM_OMSRULE .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZCAWF_VM_OMSRULE.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZCAWF_VM_OMSRULE-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZCAWF_OM_SRULE WHERE
  SRULE_ID = ZCAWF_VM_OMSRULE-SRULE_ID .
    IF SY-SUBRC = 0.
    DELETE ZCAWF_OM_SRULE .
    ENDIF.
    DELETE FROM ZCAWF_OM_SRULETX WHERE
    SRULE_ID = ZCAWF_OM_SRULE-SRULE_ID .
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZCAWF_OM_SRULE WHERE
  SRULE_ID = ZCAWF_VM_OMSRULE-SRULE_ID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZCAWF_OM_SRULE.
    ENDIF.
ZCAWF_OM_SRULE-MANDT =
ZCAWF_VM_OMSRULE-MANDT .
ZCAWF_OM_SRULE-SRULE_ID =
ZCAWF_VM_OMSRULE-SRULE_ID .
    IF SY-SUBRC = 0.
    UPDATE ZCAWF_OM_SRULE ##WARN_OK.
    ELSE.
    INSERT ZCAWF_OM_SRULE .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM ZCAWF_OM_SRULETX WHERE
    SRULE_ID = ZCAWF_OM_SRULE-SRULE_ID AND
    LANGU = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR ZCAWF_OM_SRULETX.
ZCAWF_OM_SRULETX-SRULE_ID =
ZCAWF_OM_SRULE-SRULE_ID .
ZCAWF_OM_SRULETX-LANGU =
SY-LANGU .
      ENDIF.
ZCAWF_OM_SRULETX-DESCRIPTION =
ZCAWF_VM_OMSRULE-DESCRIPTION .
ZCAWF_OM_SRULETX-DESCR_SHORT =
ZCAWF_VM_OMSRULE-DESCR_SHORT .
    IF SY-SUBRC = 0.
    UPDATE ZCAWF_OM_SRULETX ##WARN_OK.
    ELSE.
    INSERT ZCAWF_OM_SRULETX .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZCAWF_VM_OMSRULE-UPD_FLAG,
STATUS_ZCAWF_VM_OMSRULE-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZCAWF_VM_OMSRULE.
  SELECT SINGLE * FROM ZCAWF_OM_SRULE WHERE
SRULE_ID = ZCAWF_VM_OMSRULE-SRULE_ID .
ZCAWF_VM_OMSRULE-MANDT =
ZCAWF_OM_SRULE-MANDT .
ZCAWF_VM_OMSRULE-SRULE_ID =
ZCAWF_OM_SRULE-SRULE_ID .
    SELECT SINGLE * FROM ZCAWF_OM_SRULETX WHERE
SRULE_ID = ZCAWF_OM_SRULE-SRULE_ID AND
LANGU = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZCAWF_VM_OMSRULE-DESCRIPTION =
ZCAWF_OM_SRULETX-DESCRIPTION .
ZCAWF_VM_OMSRULE-DESCR_SHORT =
ZCAWF_OM_SRULETX-DESCR_SHORT .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZCAWF_VM_OMSRULE-DESCRIPTION .
      CLEAR ZCAWF_VM_OMSRULE-DESCR_SHORT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZCAWF_VM_OMSRULE USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZCAWF_VM_OMSRULE-SRULE_ID TO
ZCAWF_OM_SRULE-SRULE_ID .
MOVE ZCAWF_VM_OMSRULE-MANDT TO
ZCAWF_OM_SRULE-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZCAWF_OM_SRULE'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZCAWF_OM_SRULE TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZCAWF_OM_SRULE'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE ZCAWF_OM_SRULE-SRULE_ID TO
ZCAWF_OM_SRULETX-SRULE_ID .
MOVE SY-LANGU TO
ZCAWF_OM_SRULETX-LANGU .
MOVE ZCAWF_VM_OMSRULE-MANDT TO
ZCAWF_OM_SRULETX-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZCAWF_OM_SRULETX'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZCAWF_OM_SRULETX TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZCAWF_OM_SRULETX'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZCAWF_VM_OMTASK.................................*
FORM GET_DATA_ZCAWF_VM_OMTASK.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZCAWF_OM_SRTASK WHERE
(VIM_WHERETAB) .
    CLEAR ZCAWF_VM_OMTASK .
ZCAWF_VM_OMTASK-MANDT =
ZCAWF_OM_SRTASK-MANDT .
ZCAWF_VM_OMTASK-TASK_ID =
ZCAWF_OM_SRTASK-TASK_ID .
ZCAWF_VM_OMTASK-ENDDA =
ZCAWF_OM_SRTASK-ENDDA .
ZCAWF_VM_OMTASK-BEGDA =
ZCAWF_OM_SRTASK-BEGDA .
ZCAWF_VM_OMTASK-STEXT =
ZCAWF_OM_SRTASK-STEXT .
ZCAWF_VM_OMTASK-SHORT =
ZCAWF_OM_SRTASK-SHORT .
ZCAWF_VM_OMTASK-BEGDA_OM =
ZCAWF_OM_SRTASK-BEGDA_OM .
ZCAWF_VM_OMTASK-ENDDA_OM =
ZCAWF_OM_SRTASK-ENDDA_OM .
<VIM_TOTAL_STRUC> = ZCAWF_VM_OMTASK.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZCAWF_VM_OMTASK .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZCAWF_VM_OMTASK.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZCAWF_VM_OMTASK-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZCAWF_OM_SRTASK WHERE
  TASK_ID = ZCAWF_VM_OMTASK-TASK_ID AND
  ENDDA = ZCAWF_VM_OMTASK-ENDDA .
    IF SY-SUBRC = 0.
    DELETE ZCAWF_OM_SRTASK .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZCAWF_OM_SRTASK WHERE
  TASK_ID = ZCAWF_VM_OMTASK-TASK_ID AND
  ENDDA = ZCAWF_VM_OMTASK-ENDDA .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZCAWF_OM_SRTASK.
    ENDIF.
ZCAWF_OM_SRTASK-MANDT =
ZCAWF_VM_OMTASK-MANDT .
ZCAWF_OM_SRTASK-TASK_ID =
ZCAWF_VM_OMTASK-TASK_ID .
ZCAWF_OM_SRTASK-ENDDA =
ZCAWF_VM_OMTASK-ENDDA .
ZCAWF_OM_SRTASK-BEGDA =
ZCAWF_VM_OMTASK-BEGDA .
ZCAWF_OM_SRTASK-STEXT =
ZCAWF_VM_OMTASK-STEXT .
ZCAWF_OM_SRTASK-SHORT =
ZCAWF_VM_OMTASK-SHORT .
ZCAWF_OM_SRTASK-BEGDA_OM =
ZCAWF_VM_OMTASK-BEGDA_OM .
ZCAWF_OM_SRTASK-ENDDA_OM =
ZCAWF_VM_OMTASK-ENDDA_OM .
    IF SY-SUBRC = 0.
    UPDATE ZCAWF_OM_SRTASK ##WARN_OK.
    ELSE.
    INSERT ZCAWF_OM_SRTASK .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZCAWF_VM_OMTASK-UPD_FLAG,
STATUS_ZCAWF_VM_OMTASK-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZCAWF_VM_OMTASK.
  SELECT SINGLE * FROM ZCAWF_OM_SRTASK WHERE
TASK_ID = ZCAWF_VM_OMTASK-TASK_ID AND
ENDDA = ZCAWF_VM_OMTASK-ENDDA .
ZCAWF_VM_OMTASK-MANDT =
ZCAWF_OM_SRTASK-MANDT .
ZCAWF_VM_OMTASK-TASK_ID =
ZCAWF_OM_SRTASK-TASK_ID .
ZCAWF_VM_OMTASK-ENDDA =
ZCAWF_OM_SRTASK-ENDDA .
ZCAWF_VM_OMTASK-BEGDA =
ZCAWF_OM_SRTASK-BEGDA .
ZCAWF_VM_OMTASK-STEXT =
ZCAWF_OM_SRTASK-STEXT .
ZCAWF_VM_OMTASK-SHORT =
ZCAWF_OM_SRTASK-SHORT .
ZCAWF_VM_OMTASK-BEGDA_OM =
ZCAWF_OM_SRTASK-BEGDA_OM .
ZCAWF_VM_OMTASK-ENDDA_OM =
ZCAWF_OM_SRTASK-ENDDA_OM .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZCAWF_VM_OMTASK USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZCAWF_VM_OMTASK-TASK_ID TO
ZCAWF_OM_SRTASK-TASK_ID .
MOVE ZCAWF_VM_OMTASK-ENDDA TO
ZCAWF_OM_SRTASK-ENDDA .
MOVE ZCAWF_VM_OMTASK-MANDT TO
ZCAWF_OM_SRTASK-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZCAWF_OM_SRTASK'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZCAWF_OM_SRTASK TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZCAWF_OM_SRTASK'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZCAWF_VM_SROVJOB................................*
FORM GET_DATA_ZCAWF_VM_SROVJOB.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZCAWF_OM_SRLASSM WHERE
(VIM_WHERETAB) .
    CLEAR ZCAWF_VM_SROVJOB .
ZCAWF_VM_SROVJOB-MANDT =
ZCAWF_OM_SRLASSM-MANDT .
ZCAWF_VM_SROVJOB-SRULE_ID =
ZCAWF_OM_SRLASSM-SRULE_ID .
ZCAWF_VM_SROVJOB-SR_LEVEL =
ZCAWF_OM_SRLASSM-SR_LEVEL .
ZCAWF_VM_SROVJOB-ENDDA =
ZCAWF_OM_SRLASSM-ENDDA .
ZCAWF_VM_SROVJOB-SEQNO =
ZCAWF_OM_SRLASSM-SEQNO .
ZCAWF_VM_SROVJOB-BEGDA =
ZCAWF_OM_SRLASSM-BEGDA .
ZCAWF_VM_SROVJOB-APPROVING_JOB =
ZCAWF_OM_SRLASSM-APPROVING_JOB .
ZCAWF_VM_SROVJOB-SIGN_APPR_JOB =
ZCAWF_OM_SRLASSM-SIGN_APPR_JOB .
    SELECT * FROM ZCAWF_OM_SRJOB WHERE
JOB_ID = ZCAWF_OM_SRLASSM-APPROVING_JOB .
ZCAWF_VM_SROVJOB-DESCRIPTION_JOB =
ZCAWF_OM_SRJOB-STEXT .
      EXIT.
    ENDSELECT.
    SELECT SINGLE * FROM ZCAWF_OM_SRLVL WHERE
SRULE_ID = ZCAWF_OM_SRLASSM-SRULE_ID AND
SRULE_LEVEL = ZCAWF_OM_SRLASSM-SR_LEVEL AND
ENDDA = ZCAWF_OM_SRLASSM-ENDDA .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZCAWF_OM_SRLVLTX WHERE
SRULE_ID = ZCAWF_OM_SRLVL-SRULE_ID AND
SRULE_LEVEL = ZCAWF_OM_SRLVL-SRULE_LEVEL AND
ENDDA = ZCAWF_OM_SRLVL-ENDDA AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZCAWF_VM_SROVJOB-DESCRIPTION_LVL =
ZCAWF_OM_SRLVLTX-DESCRIPTION .
      ENDIF.
    ENDIF.
    SELECT SINGLE * FROM ZCAWF_OM_SRULE WHERE
SRULE_ID = ZCAWF_OM_SRLASSM-SRULE_ID .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZCAWF_OM_SRULETX WHERE
SRULE_ID = ZCAWF_OM_SRULE-SRULE_ID AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZCAWF_VM_SROVJOB-DESCRIPTION_RULE =
ZCAWF_OM_SRULETX-DESCRIPTION .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZCAWF_VM_SROVJOB.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZCAWF_VM_SROVJOB .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZCAWF_VM_SROVJOB.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZCAWF_VM_SROVJOB-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZCAWF_OM_SRLASSM WHERE
  SRULE_ID = ZCAWF_VM_SROVJOB-SRULE_ID AND
  SR_LEVEL = ZCAWF_VM_SROVJOB-SR_LEVEL AND
  ENDDA = ZCAWF_VM_SROVJOB-ENDDA AND
  SEQNO = ZCAWF_VM_SROVJOB-SEQNO .
    IF SY-SUBRC = 0.
    DELETE ZCAWF_OM_SRLASSM .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZCAWF_OM_SRLASSM WHERE
  SRULE_ID = ZCAWF_VM_SROVJOB-SRULE_ID AND
  SR_LEVEL = ZCAWF_VM_SROVJOB-SR_LEVEL AND
  ENDDA = ZCAWF_VM_SROVJOB-ENDDA AND
  SEQNO = ZCAWF_VM_SROVJOB-SEQNO .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZCAWF_OM_SRLASSM.
    ENDIF.
ZCAWF_OM_SRLASSM-MANDT =
ZCAWF_VM_SROVJOB-MANDT .
ZCAWF_OM_SRLASSM-SRULE_ID =
ZCAWF_VM_SROVJOB-SRULE_ID .
ZCAWF_OM_SRLASSM-SR_LEVEL =
ZCAWF_VM_SROVJOB-SR_LEVEL .
ZCAWF_OM_SRLASSM-ENDDA =
ZCAWF_VM_SROVJOB-ENDDA .
ZCAWF_OM_SRLASSM-SEQNO =
ZCAWF_VM_SROVJOB-SEQNO .
ZCAWF_OM_SRLASSM-BEGDA =
ZCAWF_VM_SROVJOB-BEGDA .
ZCAWF_OM_SRLASSM-APPROVING_JOB =
ZCAWF_VM_SROVJOB-APPROVING_JOB .
ZCAWF_OM_SRLASSM-SIGN_APPR_JOB =
ZCAWF_VM_SROVJOB-SIGN_APPR_JOB .
    IF SY-SUBRC = 0.
    UPDATE ZCAWF_OM_SRLASSM ##WARN_OK.
    ELSE.
    INSERT ZCAWF_OM_SRLASSM .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZCAWF_VM_SROVJOB-UPD_FLAG,
STATUS_ZCAWF_VM_SROVJOB-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZCAWF_VM_SROVJOB.
  SELECT SINGLE * FROM ZCAWF_OM_SRLASSM WHERE
SRULE_ID = ZCAWF_VM_SROVJOB-SRULE_ID AND
SR_LEVEL = ZCAWF_VM_SROVJOB-SR_LEVEL AND
ENDDA = ZCAWF_VM_SROVJOB-ENDDA AND
SEQNO = ZCAWF_VM_SROVJOB-SEQNO .
ZCAWF_VM_SROVJOB-MANDT =
ZCAWF_OM_SRLASSM-MANDT .
ZCAWF_VM_SROVJOB-SRULE_ID =
ZCAWF_OM_SRLASSM-SRULE_ID .
ZCAWF_VM_SROVJOB-SR_LEVEL =
ZCAWF_OM_SRLASSM-SR_LEVEL .
ZCAWF_VM_SROVJOB-ENDDA =
ZCAWF_OM_SRLASSM-ENDDA .
ZCAWF_VM_SROVJOB-SEQNO =
ZCAWF_OM_SRLASSM-SEQNO .
ZCAWF_VM_SROVJOB-BEGDA =
ZCAWF_OM_SRLASSM-BEGDA .
ZCAWF_VM_SROVJOB-APPROVING_JOB =
ZCAWF_OM_SRLASSM-APPROVING_JOB .
ZCAWF_VM_SROVJOB-SIGN_APPR_JOB =
ZCAWF_OM_SRLASSM-SIGN_APPR_JOB .
    SELECT * FROM ZCAWF_OM_SRJOB WHERE
JOB_ID = ZCAWF_OM_SRLASSM-APPROVING_JOB .
ZCAWF_VM_SROVJOB-DESCRIPTION_JOB =
ZCAWF_OM_SRJOB-STEXT .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR ZCAWF_VM_SROVJOB-DESCRIPTION_JOB .
    ENDIF.
    SELECT SINGLE * FROM ZCAWF_OM_SRLVL WHERE
SRULE_ID = ZCAWF_OM_SRLASSM-SRULE_ID AND
SRULE_LEVEL = ZCAWF_OM_SRLASSM-SR_LEVEL AND
ENDDA = ZCAWF_OM_SRLASSM-ENDDA .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZCAWF_OM_SRLVLTX WHERE
SRULE_ID = ZCAWF_OM_SRLVL-SRULE_ID AND
SRULE_LEVEL = ZCAWF_OM_SRLVL-SRULE_LEVEL AND
ENDDA = ZCAWF_OM_SRLVL-ENDDA AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZCAWF_VM_SROVJOB-DESCRIPTION_LVL =
ZCAWF_OM_SRLVLTX-DESCRIPTION .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZCAWF_VM_SROVJOB-DESCRIPTION_LVL .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZCAWF_VM_SROVJOB-DESCRIPTION_LVL .
    ENDIF.
    SELECT SINGLE * FROM ZCAWF_OM_SRULE WHERE
SRULE_ID = ZCAWF_OM_SRLASSM-SRULE_ID .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZCAWF_OM_SRULETX WHERE
SRULE_ID = ZCAWF_OM_SRULE-SRULE_ID AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZCAWF_VM_SROVJOB-DESCRIPTION_RULE =
ZCAWF_OM_SRULETX-DESCRIPTION .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZCAWF_VM_SROVJOB-DESCRIPTION_RULE .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZCAWF_VM_SROVJOB-DESCRIPTION_RULE .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZCAWF_VM_SROVJOB USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZCAWF_VM_SROVJOB-SRULE_ID TO
ZCAWF_OM_SRLASSM-SRULE_ID .
MOVE ZCAWF_VM_SROVJOB-SR_LEVEL TO
ZCAWF_OM_SRLASSM-SR_LEVEL .
MOVE ZCAWF_VM_SROVJOB-ENDDA TO
ZCAWF_OM_SRLASSM-ENDDA .
MOVE ZCAWF_VM_SROVJOB-SEQNO TO
ZCAWF_OM_SRLASSM-SEQNO .
MOVE ZCAWF_VM_SROVJOB-MANDT TO
ZCAWF_OM_SRLASSM-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZCAWF_OM_SRLASSM'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZCAWF_OM_SRLASSM TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZCAWF_OM_SRLASSM'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZCAWF_VM_SROVJOB USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZCAWF_OM_SRLASSM-MANDT =
ZCAWF_VM_SROVJOB-MANDT .
ZCAWF_OM_SRLASSM-SRULE_ID =
ZCAWF_VM_SROVJOB-SRULE_ID .
ZCAWF_OM_SRLASSM-SR_LEVEL =
ZCAWF_VM_SROVJOB-SR_LEVEL .
ZCAWF_OM_SRLASSM-ENDDA =
ZCAWF_VM_SROVJOB-ENDDA .
ZCAWF_OM_SRLASSM-SEQNO =
ZCAWF_VM_SROVJOB-SEQNO .
ZCAWF_OM_SRLASSM-BEGDA =
ZCAWF_VM_SROVJOB-BEGDA .
ZCAWF_OM_SRLASSM-APPROVING_JOB =
ZCAWF_VM_SROVJOB-APPROVING_JOB .
ZCAWF_OM_SRLASSM-SIGN_APPR_JOB =
ZCAWF_VM_SROVJOB-SIGN_APPR_JOB .
    SELECT * FROM ZCAWF_OM_SRJOB WHERE
JOB_ID = ZCAWF_OM_SRLASSM-APPROVING_JOB .
ZCAWF_VM_SROVJOB-DESCRIPTION_JOB =
ZCAWF_OM_SRJOB-STEXT .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR ZCAWF_VM_SROVJOB-DESCRIPTION_JOB .
    ENDIF.
    SELECT SINGLE * FROM ZCAWF_OM_SRLVL WHERE
SRULE_ID = ZCAWF_OM_SRLASSM-SRULE_ID AND
SRULE_LEVEL = ZCAWF_OM_SRLASSM-SR_LEVEL AND
ENDDA = ZCAWF_OM_SRLASSM-ENDDA .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZCAWF_OM_SRLVLTX WHERE
SRULE_ID = ZCAWF_OM_SRLVL-SRULE_ID AND
SRULE_LEVEL = ZCAWF_OM_SRLVL-SRULE_LEVEL AND
ENDDA = ZCAWF_OM_SRLVL-ENDDA AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZCAWF_VM_SROVJOB-DESCRIPTION_LVL =
ZCAWF_OM_SRLVLTX-DESCRIPTION .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZCAWF_VM_SROVJOB-DESCRIPTION_LVL .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZCAWF_VM_SROVJOB-DESCRIPTION_LVL .
    ENDIF.
    SELECT SINGLE * FROM ZCAWF_OM_SRULE WHERE
SRULE_ID = ZCAWF_OM_SRLASSM-SRULE_ID .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZCAWF_OM_SRULETX WHERE
SRULE_ID = ZCAWF_OM_SRULE-SRULE_ID AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZCAWF_VM_SROVJOB-DESCRIPTION_RULE =
ZCAWF_OM_SRULETX-DESCRIPTION .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZCAWF_VM_SROVJOB-DESCRIPTION_RULE .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZCAWF_VM_SROVJOB-DESCRIPTION_RULE .
    ENDIF.
ENDFORM.
*...processing: ZCAWF_VM_SROVTSK................................*
FORM GET_DATA_ZCAWF_VM_SROVTSK.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZCAWF_OM_SRLASSM WHERE
    TASK_2_DELEGATE NE '00000000' AND
(VIM_WHERETAB) .
    CLEAR ZCAWF_VM_SROVTSK .
ZCAWF_VM_SROVTSK-MANDT =
ZCAWF_OM_SRLASSM-MANDT .
ZCAWF_VM_SROVTSK-SRULE_ID =
ZCAWF_OM_SRLASSM-SRULE_ID .
ZCAWF_VM_SROVTSK-SR_LEVEL =
ZCAWF_OM_SRLASSM-SR_LEVEL .
ZCAWF_VM_SROVTSK-ENDDA =
ZCAWF_OM_SRLASSM-ENDDA .
ZCAWF_VM_SROVTSK-SEQNO =
ZCAWF_OM_SRLASSM-SEQNO .
ZCAWF_VM_SROVTSK-BEGDA =
ZCAWF_OM_SRLASSM-BEGDA .
ZCAWF_VM_SROVTSK-TASK_2_DELEGATE =
ZCAWF_OM_SRLASSM-TASK_2_DELEGATE .
    SELECT SINGLE * FROM ZCAWF_OM_SRLVL WHERE
SRULE_ID = ZCAWF_OM_SRLASSM-SRULE_ID AND
SRULE_LEVEL = ZCAWF_OM_SRLASSM-SR_LEVEL AND
ENDDA = ZCAWF_OM_SRLASSM-ENDDA .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZCAWF_OM_SRLVLTX WHERE
SRULE_ID = ZCAWF_OM_SRLVL-SRULE_ID AND
SRULE_LEVEL = ZCAWF_OM_SRLVL-SRULE_LEVEL AND
ENDDA = ZCAWF_OM_SRLVL-ENDDA AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZCAWF_VM_SROVTSK-DESCRIPTION_LVL =
ZCAWF_OM_SRLVLTX-DESCRIPTION .
      ENDIF.
    ENDIF.
    SELECT * FROM ZCAWF_OM_SRTASK WHERE
TASK_ID = ZCAWF_OM_SRLASSM-TASK_2_DELEGATE .
ZCAWF_VM_SROVTSK-DESCRIPTION_TASK =
ZCAWF_OM_SRTASK-STEXT .
      EXIT.
    ENDSELECT.
    SELECT SINGLE * FROM ZCAWF_OM_SRULE WHERE
SRULE_ID = ZCAWF_OM_SRLASSM-SRULE_ID .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZCAWF_OM_SRULETX WHERE
SRULE_ID = ZCAWF_OM_SRULE-SRULE_ID AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZCAWF_VM_SROVTSK-DESCRIPTION_RULE =
ZCAWF_OM_SRULETX-DESCRIPTION .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZCAWF_VM_SROVTSK.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZCAWF_VM_SROVTSK .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZCAWF_VM_SROVTSK.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZCAWF_VM_SROVTSK-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZCAWF_OM_SRLASSM WHERE
  SRULE_ID = ZCAWF_VM_SROVTSK-SRULE_ID AND
  SR_LEVEL = ZCAWF_VM_SROVTSK-SR_LEVEL AND
  ENDDA = ZCAWF_VM_SROVTSK-ENDDA AND
  SEQNO = ZCAWF_VM_SROVTSK-SEQNO .
    IF SY-SUBRC = 0.
    DELETE ZCAWF_OM_SRLASSM .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZCAWF_OM_SRLASSM WHERE
  SRULE_ID = ZCAWF_VM_SROVTSK-SRULE_ID AND
  SR_LEVEL = ZCAWF_VM_SROVTSK-SR_LEVEL AND
  ENDDA = ZCAWF_VM_SROVTSK-ENDDA AND
  SEQNO = ZCAWF_VM_SROVTSK-SEQNO .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZCAWF_OM_SRLASSM.
    ENDIF.
ZCAWF_OM_SRLASSM-MANDT =
ZCAWF_VM_SROVTSK-MANDT .
ZCAWF_OM_SRLASSM-SRULE_ID =
ZCAWF_VM_SROVTSK-SRULE_ID .
ZCAWF_OM_SRLASSM-SR_LEVEL =
ZCAWF_VM_SROVTSK-SR_LEVEL .
ZCAWF_OM_SRLASSM-ENDDA =
ZCAWF_VM_SROVTSK-ENDDA .
ZCAWF_OM_SRLASSM-SEQNO =
ZCAWF_VM_SROVTSK-SEQNO .
ZCAWF_OM_SRLASSM-BEGDA =
ZCAWF_VM_SROVTSK-BEGDA .
ZCAWF_OM_SRLASSM-TASK_2_DELEGATE =
ZCAWF_VM_SROVTSK-TASK_2_DELEGATE .
    IF SY-SUBRC = 0.
    UPDATE ZCAWF_OM_SRLASSM ##WARN_OK.
    ELSE.
    INSERT ZCAWF_OM_SRLASSM .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZCAWF_VM_SROVTSK-UPD_FLAG,
STATUS_ZCAWF_VM_SROVTSK-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZCAWF_VM_SROVTSK.
  SELECT SINGLE * FROM ZCAWF_OM_SRLASSM WHERE
SRULE_ID = ZCAWF_VM_SROVTSK-SRULE_ID AND
SR_LEVEL = ZCAWF_VM_SROVTSK-SR_LEVEL AND
ENDDA = ZCAWF_VM_SROVTSK-ENDDA AND
SEQNO = ZCAWF_VM_SROVTSK-SEQNO .
ZCAWF_VM_SROVTSK-MANDT =
ZCAWF_OM_SRLASSM-MANDT .
ZCAWF_VM_SROVTSK-SRULE_ID =
ZCAWF_OM_SRLASSM-SRULE_ID .
ZCAWF_VM_SROVTSK-SR_LEVEL =
ZCAWF_OM_SRLASSM-SR_LEVEL .
ZCAWF_VM_SROVTSK-ENDDA =
ZCAWF_OM_SRLASSM-ENDDA .
ZCAWF_VM_SROVTSK-SEQNO =
ZCAWF_OM_SRLASSM-SEQNO .
ZCAWF_VM_SROVTSK-BEGDA =
ZCAWF_OM_SRLASSM-BEGDA .
ZCAWF_VM_SROVTSK-TASK_2_DELEGATE =
ZCAWF_OM_SRLASSM-TASK_2_DELEGATE .
    SELECT SINGLE * FROM ZCAWF_OM_SRLVL WHERE
SRULE_ID = ZCAWF_OM_SRLASSM-SRULE_ID AND
SRULE_LEVEL = ZCAWF_OM_SRLASSM-SR_LEVEL AND
ENDDA = ZCAWF_OM_SRLASSM-ENDDA .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZCAWF_OM_SRLVLTX WHERE
SRULE_ID = ZCAWF_OM_SRLVL-SRULE_ID AND
SRULE_LEVEL = ZCAWF_OM_SRLVL-SRULE_LEVEL AND
ENDDA = ZCAWF_OM_SRLVL-ENDDA AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZCAWF_VM_SROVTSK-DESCRIPTION_LVL =
ZCAWF_OM_SRLVLTX-DESCRIPTION .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZCAWF_VM_SROVTSK-DESCRIPTION_LVL .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZCAWF_VM_SROVTSK-DESCRIPTION_LVL .
    ENDIF.
    SELECT * FROM ZCAWF_OM_SRTASK WHERE
TASK_ID = ZCAWF_OM_SRLASSM-TASK_2_DELEGATE .
ZCAWF_VM_SROVTSK-DESCRIPTION_TASK =
ZCAWF_OM_SRTASK-STEXT .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR ZCAWF_VM_SROVTSK-DESCRIPTION_TASK .
    ENDIF.
    SELECT SINGLE * FROM ZCAWF_OM_SRULE WHERE
SRULE_ID = ZCAWF_OM_SRLASSM-SRULE_ID .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZCAWF_OM_SRULETX WHERE
SRULE_ID = ZCAWF_OM_SRULE-SRULE_ID AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZCAWF_VM_SROVTSK-DESCRIPTION_RULE =
ZCAWF_OM_SRULETX-DESCRIPTION .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZCAWF_VM_SROVTSK-DESCRIPTION_RULE .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZCAWF_VM_SROVTSK-DESCRIPTION_RULE .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZCAWF_VM_SROVTSK USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZCAWF_VM_SROVTSK-SRULE_ID TO
ZCAWF_OM_SRLASSM-SRULE_ID .
MOVE ZCAWF_VM_SROVTSK-SR_LEVEL TO
ZCAWF_OM_SRLASSM-SR_LEVEL .
MOVE ZCAWF_VM_SROVTSK-ENDDA TO
ZCAWF_OM_SRLASSM-ENDDA .
MOVE ZCAWF_VM_SROVTSK-SEQNO TO
ZCAWF_OM_SRLASSM-SEQNO .
MOVE ZCAWF_VM_SROVTSK-MANDT TO
ZCAWF_OM_SRLASSM-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZCAWF_OM_SRLASSM'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZCAWF_OM_SRLASSM TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZCAWF_OM_SRLASSM'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZCAWF_VM_SROVTSK USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZCAWF_OM_SRLASSM-MANDT =
ZCAWF_VM_SROVTSK-MANDT .
ZCAWF_OM_SRLASSM-SRULE_ID =
ZCAWF_VM_SROVTSK-SRULE_ID .
ZCAWF_OM_SRLASSM-SR_LEVEL =
ZCAWF_VM_SROVTSK-SR_LEVEL .
ZCAWF_OM_SRLASSM-ENDDA =
ZCAWF_VM_SROVTSK-ENDDA .
ZCAWF_OM_SRLASSM-SEQNO =
ZCAWF_VM_SROVTSK-SEQNO .
ZCAWF_OM_SRLASSM-BEGDA =
ZCAWF_VM_SROVTSK-BEGDA .
ZCAWF_OM_SRLASSM-TASK_2_DELEGATE =
ZCAWF_VM_SROVTSK-TASK_2_DELEGATE .
    SELECT SINGLE * FROM ZCAWF_OM_SRLVL WHERE
SRULE_ID = ZCAWF_OM_SRLASSM-SRULE_ID AND
SRULE_LEVEL = ZCAWF_OM_SRLASSM-SR_LEVEL AND
ENDDA = ZCAWF_OM_SRLASSM-ENDDA .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZCAWF_OM_SRLVLTX WHERE
SRULE_ID = ZCAWF_OM_SRLVL-SRULE_ID AND
SRULE_LEVEL = ZCAWF_OM_SRLVL-SRULE_LEVEL AND
ENDDA = ZCAWF_OM_SRLVL-ENDDA AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZCAWF_VM_SROVTSK-DESCRIPTION_LVL =
ZCAWF_OM_SRLVLTX-DESCRIPTION .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZCAWF_VM_SROVTSK-DESCRIPTION_LVL .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZCAWF_VM_SROVTSK-DESCRIPTION_LVL .
    ENDIF.
    SELECT * FROM ZCAWF_OM_SRTASK WHERE
TASK_ID = ZCAWF_OM_SRLASSM-TASK_2_DELEGATE .
ZCAWF_VM_SROVTSK-DESCRIPTION_TASK =
ZCAWF_OM_SRTASK-STEXT .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR ZCAWF_VM_SROVTSK-DESCRIPTION_TASK .
    ENDIF.
    SELECT SINGLE * FROM ZCAWF_OM_SRULE WHERE
SRULE_ID = ZCAWF_OM_SRLASSM-SRULE_ID .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZCAWF_OM_SRULETX WHERE
SRULE_ID = ZCAWF_OM_SRULE-SRULE_ID AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZCAWF_VM_SROVTSK-DESCRIPTION_RULE =
ZCAWF_OM_SRULETX-DESCRIPTION .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZCAWF_VM_SROVTSK-DESCRIPTION_RULE .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZCAWF_VM_SROVTSK-DESCRIPTION_RULE .
    ENDIF.
ENDFORM.
