* VCL-Modifications
PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCAWF_VM_SROVJOB CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZCAWF_VM_SROVJOB-SRULE_ID .
    FIELD ZCAWF_VM_SROVJOB-SR_LEVEL .
    FIELD ZCAWF_VM_SROVJOB-ENDDA .
    FIELD ZCAWF_VM_SROVJOB-SEQNO .
    FIELD ZCAWF_VM_SROVJOB-BEGDA .
    FIELD ZCAWF_VM_SROVJOB-APPROVING_JOB .
    FIELD ZCAWF_VM_SROVJOB-SIGN_APPR_JOB .
    FIELD ZCAWF_VM_SROVJOB-DESCRIPTION_JOB .
    FIELD ZCAWF_VM_SROVJOB-DESCRIPTION_LVL .
    FIELD ZCAWF_VM_SROVJOB-DESCRIPTION_RULE .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
    MODULE COMPLETE_ZCAWF_VM_SROVJOB ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZCAWF_VM_SROVJOB-SRULE_ID .
    FIELD ZCAWF_VM_SROVJOB-SR_LEVEL .
    FIELD ZCAWF_VM_SROVJOB-ENDDA .
    FIELD ZCAWF_VM_SROVJOB-SEQNO .
    FIELD ZCAWF_VM_SROVJOB-APPROVING_JOB.
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
*
PROCESS ON VALUE-REQUEST.
    FIELD  ZCAWF_VM_SROVJOB-SR_LEVEL MODULE VCL_HELP_VALUES.
    FIELD  ZCAWF_VM_SROVJOB-SRULE_ID MODULE VCL_HELP_VALUES.
    FIELD  ZCAWF_VM_SROVJOB-APPROVING_JOB MODULE VCL_HELP_VALUES.
