PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCAWF_VM_OMJOB CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
   MODULE LISTE_DEACTIVATE.                         "SCH-20250727-193127
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZCAWF_VM_OMJOB-JOB_ID .
    FIELD ZCAWF_VM_OMJOB-ENDDA .
    FIELD ZCAWF_VM_OMJOB-BEGDA .
    FIELD ZCAWF_VM_OMJOB-STEXT .
    FIELD ZCAWF_VM_OMJOB-SHORT .
    FIELD ZCAWF_VM_OMJOB-BEGDA_OM .
    FIELD ZCAWF_VM_OMJOB-ENDDA_OM .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   CHAIN.                                           "SCH-20250727-193127
    FIELD ZCAWF_VM_OMJOB-BEGDA.                     "SCH-20250727-193127
    FIELD ZCAWF_VM_OMJOB-ENDDA.                     "SCH-20250727-193127
    MODULE TEMP_DELIMITATION ON CHAIN-REQUEST.      "SCH-20250727-193127
   ENDCHAIN.                                        "SCH-20250727-193127
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZCAWF_VM_OMJOB-JOB_ID .
    FIELD ZCAWF_VM_OMJOB-ENDDA .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
