* VCL-Modifications
PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCAWF_VM_SROVTSK CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZCAWF_VM_SROVTSK-SRULE_ID .
    FIELD ZCAWF_VM_SROVTSK-SR_LEVEL .
    FIELD ZCAWF_VM_SROVTSK-ENDDA .
    FIELD ZCAWF_VM_SROVTSK-SEQNO .
    FIELD ZCAWF_VM_SROVTSK-BEGDA .
    FIELD ZCAWF_VM_SROVTSK-TASK_2_DELEGATE .
    FIELD ZCAWF_VM_SROVTSK-DESCRIPTION_TASK .
    FIELD ZCAWF_VM_SROVTSK-DESCRIPTION_LVL .
    FIELD ZCAWF_VM_SROVTSK-DESCRIPTION_RULE .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
    MODULE COMPLETE_ZCAWF_VM_SROVTSK ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZCAWF_VM_SROVTSK-SRULE_ID .
    FIELD ZCAWF_VM_SROVTSK-SR_LEVEL .
    FIELD ZCAWF_VM_SROVTSK-ENDDA .
    FIELD ZCAWF_VM_SROVTSK-SEQNO .
    FIELD ZCAWF_VM_SROVTSK-TASK_2_DELEGATE.
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
*
PROCESS ON VALUE-REQUEST.
    FIELD  ZCAWF_VM_SROVTSK-TASK_2_DELEGATE MODULE VCL_HELP_VALUES.
    FIELD  ZCAWF_VM_SROVTSK-SR_LEVEL MODULE VCL_HELP_VALUES.
    FIELD  ZCAWF_VM_SROVTSK-SRULE_ID MODULE VCL_HELP_VALUES.
