*---------------------------------------------------------------------*
*    view related data declarations
*---------------------------------------------------------------------*
*...processing: ZCAWF_VM_OMJOB..................................*
TABLES: ZCAWF_VM_OMJOB, *ZCAWF_VM_OMJOB. "view work areas
CONTROLS: TCTRL_ZCAWF_VM_OMJOB
TYPE TABLEVIEW USING SCREEN '0001'.
DATA: BEGIN OF STATUS_ZCAWF_VM_OMJOB. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZCAWF_VM_OMJOB.
* Table for entries selected to show on screen
DATA: BEGIN OF ZCAWF_VM_OMJOB_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZCAWF_VM_OMJOB.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZCAWF_VM_OMJOB_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZCAWF_VM_OMJOB_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZCAWF_VM_OMJOB.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZCAWF_VM_OMJOB_TOTAL.

*...processing: ZCAWF_VM_OMSRLAS................................*
TABLES: ZCAWF_VM_OMSRLAS, *ZCAWF_VM_OMSRLAS. "view work areas
CONTROLS: TCTRL_ZCAWF_VM_OMSRLAS
TYPE TABLEVIEW USING SCREEN '0005'.
DATA: BEGIN OF STATUS_ZCAWF_VM_OMSRLAS. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZCAWF_VM_OMSRLAS.
* Table for entries selected to show on screen
DATA: BEGIN OF ZCAWF_VM_OMSRLAS_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZCAWF_VM_OMSRLAS.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZCAWF_VM_OMSRLAS_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZCAWF_VM_OMSRLAS_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZCAWF_VM_OMSRLAS.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZCAWF_VM_OMSRLAS_TOTAL.

*...processing: ZCAWF_VM_OMSRLVL................................*
TABLES: ZCAWF_VM_OMSRLVL, *ZCAWF_VM_OMSRLVL. "view work areas
CONTROLS: TCTRL_ZCAWF_VM_OMSRLVL
TYPE TABLEVIEW USING SCREEN '0004'.
DATA: BEGIN OF STATUS_ZCAWF_VM_OMSRLVL. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZCAWF_VM_OMSRLVL.
* Table for entries selected to show on screen
DATA: BEGIN OF ZCAWF_VM_OMSRLVL_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZCAWF_VM_OMSRLVL.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZCAWF_VM_OMSRLVL_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZCAWF_VM_OMSRLVL_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZCAWF_VM_OMSRLVL.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZCAWF_VM_OMSRLVL_TOTAL.

*...processing: ZCAWF_VM_OMSRULE................................*
TABLES: ZCAWF_VM_OMSRULE, *ZCAWF_VM_OMSRULE. "view work areas
CONTROLS: TCTRL_ZCAWF_VM_OMSRULE
TYPE TABLEVIEW USING SCREEN '0003'.
DATA: BEGIN OF STATUS_ZCAWF_VM_OMSRULE. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZCAWF_VM_OMSRULE.
* Table for entries selected to show on screen
DATA: BEGIN OF ZCAWF_VM_OMSRULE_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZCAWF_VM_OMSRULE.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZCAWF_VM_OMSRULE_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZCAWF_VM_OMSRULE_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZCAWF_VM_OMSRULE.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZCAWF_VM_OMSRULE_TOTAL.

*...processing: ZCAWF_VM_OMTASK.................................*
TABLES: ZCAWF_VM_OMTASK, *ZCAWF_VM_OMTASK. "view work areas
CONTROLS: TCTRL_ZCAWF_VM_OMTASK
TYPE TABLEVIEW USING SCREEN '0002'.
DATA: BEGIN OF STATUS_ZCAWF_VM_OMTASK. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZCAWF_VM_OMTASK.
* Table for entries selected to show on screen
DATA: BEGIN OF ZCAWF_VM_OMTASK_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZCAWF_VM_OMTASK.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZCAWF_VM_OMTASK_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZCAWF_VM_OMTASK_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZCAWF_VM_OMTASK.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZCAWF_VM_OMTASK_TOTAL.

*...processing: ZCAWF_VM_SROVJOB................................*
TABLES: ZCAWF_VM_SROVJOB, *ZCAWF_VM_SROVJOB. "view work areas
CONTROLS: TCTRL_ZCAWF_VM_SROVJOB
TYPE TABLEVIEW USING SCREEN '0006'.
DATA: BEGIN OF STATUS_ZCAWF_VM_SROVJOB. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZCAWF_VM_SROVJOB.
* Table for entries selected to show on screen
DATA: BEGIN OF ZCAWF_VM_SROVJOB_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZCAWF_VM_SROVJOB.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZCAWF_VM_SROVJOB_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZCAWF_VM_SROVJOB_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZCAWF_VM_SROVJOB.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZCAWF_VM_SROVJOB_TOTAL.

*...processing: ZCAWF_VM_SROVTSK................................*
TABLES: ZCAWF_VM_SROVTSK, *ZCAWF_VM_SROVTSK. "view work areas
CONTROLS: TCTRL_ZCAWF_VM_SROVTSK
TYPE TABLEVIEW USING SCREEN '0007'.
DATA: BEGIN OF STATUS_ZCAWF_VM_SROVTSK. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZCAWF_VM_SROVTSK.
* Table for entries selected to show on screen
DATA: BEGIN OF ZCAWF_VM_SROVTSK_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZCAWF_VM_SROVTSK.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZCAWF_VM_SROVTSK_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZCAWF_VM_SROVTSK_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZCAWF_VM_SROVTSK.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZCAWF_VM_SROVTSK_TOTAL.

*.........table declarations:.................................*
TABLES: ZCAWF_OM_SRJOB                 .
TABLES: ZCAWF_OM_SRLASSM               .
TABLES: ZCAWF_OM_SRLVL                 .
TABLES: ZCAWF_OM_SRLVLTX               .
TABLES: ZCAWF_OM_SRTASK                .
TABLES: ZCAWF_OM_SRULE                 .
TABLES: ZCAWF_OM_SRULETX               .
